version: '3.4'
services:
  avalanchego.avado.dnp.dappnode.eth:
    image: 'avalanchego.avado.dnp.dappnode.eth:0.1.18'
    build:
      context: ./build
      args:
        - VERSION=0.8.4
    environment:
      - EXTRA_OPTS=
    volumes:
      - 'data:/data'
    ports:
      - '9650:9650'
      - '81:81'
volumes:
  data: {}
  logs: {}
